### ISSUE TITLE
Linter reports error for comment on first line of document

### ISSUE THREAD

**Issue by hhercules** [mschuchard/linter-terraform-syntax#1]
Linter version 1.1.0

<img width="664" alt="screen shot 2016-12-30 at 9 37 01 am" src="https://cloud.githubusercontent.com/assets/8095637/21569650/a9928a50-ce73-11e6-9533-c6040f6b894a.png">

**Comment by mschuchard** [comment]
That message should be taken literally. It means somewhere in the directory that file is located, you have a file (including possibly that one) which is failing either `terraform validate` or `terraform plan` for reasons unrelated to a syntax error. If you run validate or plan on the directory, the true error will be shown.

In the next version to be released, the linter will display the actual error message related to what is wrong in the directory the file is in. Unfortunately, terraform does not display the file with the issue for non-syntax errors, so I cannot capture that in the linter.

**Comment by hhercules** [comment]
Ah make sense so it is not pointing at the comment, but rather because I have not completed all my changes something is wrong still. THANK YOU!

**Comment by mschuchard** [comment]
Sure; I guess I should get the next release out a little sooner. I will try for the next week.
