### ISSUE TITLE
error running linter on terraform.tf files

### ISSUE THREAD

**Issue by eshwar976** [mschuchard/linter-terraform-syntax#10]
/Users//.atom/packages/kite/node_modules/rollbar/dist/rollbar.js:4849 [Linter] Error running Terraform Error: spawn xxxxx ENOENT
    at exports._errnoException (util.js:1050)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193)
    at onErrorNT (internal/child_process.js:367)
    at _combinedTickCallback (internal/process/next_tick.js:80)
    at process._tickCallback (internal/process/next_tick.js:104)

**Comment by mschuchard** [comment]
The issue tracker is not really for technical support. If you provide more information, I may be able to help, but you also may have better success at a dedicated website like the StackExchange network.

**Comment by benpoliquin** [comment]
I am running into this _identical_ issue.

**Comment by phlegx** [comment]
Hi @mschuchard I have also this issue:

Error points to these files

`~/.atom/packages/linter-docker/node_modules/sb-exec/lib/index.js` line 89

and 

 `~/.atom/packages/linter/lib/linter-registry.js` line 154

**Comment by mschuchard** [comment]
@phlegx You have an actual issue that may be related to the code and is not technical support, and is also unrelated to the original. Please open a new issue on the tracker.
