### ISSUE TITLE
[Linter] Error running Terraform Error: Process execution timed out

### ISSUE THREAD

**Issue by phlegx** [mschuchard/linter-terraform-syntax#16]
Hi @mschuchard. Running your Atom plugin results in the following error:

```[Linter] Error running Terraform Error: Process execution timed out```

Error points to these files

`~/.atom/packages/linter-docker/node_modules/sb-exec/lib/index.js` line `89`

and 

 `~/.atom/packages/linter/lib/linter-registry.js` line `154`

If you have any ideas what might cause that and how to fix it, let me know.

**Comment by mschuchard** [comment]
Do you see this error thrown for all modules, or only for the largest modules? If you have a module with a small `main.tf` do you see this error?

**Comment by phlegx** [comment]
@mschuchard Sorry for the late reply. The small `main.tf` files do not seem to throw/force that error. It seems indeed to happen only on larger files/modules.

**Comment by mschuchard** [comment]
Ok I will add a configuration option to increase the timeout for the Terraform CLI execution. After that, you can patch locally, test, and see if it works for you.

**Comment by mschuchard** [comment]
You can replace the `lib/main.js` in your locally installed package with the one here. Try the new `timeout` config setting and see if it helps with your issue.

**Comment by phlegx** [comment]
Dear @mschuchard I tried your updated code, and as far as I have seen there was no error anymore for the `Process execution timeout` up until now. Seems that this has fixed it.

**Comment by phlegx** [comment]
`Update` Error happened again with 10 seconds. I now set 20 seconds, Error still there and the machine starts slowing down

**Comment by mschuchard** [comment]
Can you show the return from executing `terraform validate` in that project directory?

**Comment by mschuchard** [comment]
No update in three months; closing.
