### ISSUE TITLE
Support indented heredoc string variant that is introduced by the <<- sequence

### ISSUE THREAD

**Issue by mark-greene** [mschuchard/linter-terraform-syntax#18]
Terraform accepts an indented heredoc string variant that is introduced by the <<- sequence.
```
block {
  value = <<-EOT
  hello
    world
  EOT
}
```

https://www.terraform.io/docs/configuration/expressions.html#string-literals

**Comment by mschuchard** [comment]
This package will validate and format your Terraform config files. If you need syntax highlighting and DSL recognition, please refer to the `language-terraform` package issue tracker. If your version of Terraform does not recognize your syntax, please refer to the Terraform issue tracker. Syntax recognition is completely external to this package.
