### ISSUE TITLE
not running format

### ISSUE THREAD

**Issue by evanstoddard23** [mschuchard/linter-terraform-syntax#20]
I have "Use Terraform Fmt" selected which says it runs before linting but it never does.

**Comment by nergdron** [comment]
also running into this, Atom 1.48.0, terraform 0.13.5, linter-terraform-syntax version 1.5.0.

**Comment by nergdron** [comment]
in fact in mine, it wasn't running in linter or format mode. some further digging, it looks like something is breaking when using the hcl language provider (https://github.com/fd/language-hcl). when I switch to the terraform specific language support for a file (https://github.com/cmur2/language-terraform) then linting and formatting appear to work fine.

**Comment by nergdron** [comment]
ahhh I may have spoken too soon. when there's an actual syntax error, linting works correctly. but if it's just a warning, (such as for deprecations), the linting messages don't show up. so even without the HCL language provider active, there's still some inconsistent weirdness.

**Comment by mschuchard** [comment]
@nergdron Please open a new issue for your situation as it is different.
Also, closing this due to lack of MCVE and description.
