### ISSUE TITLE
Error: spawn terraform ENOENT

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [mschuchard/linter-terraform-syntax#4]
Hi,
I am getting the following Error in Atom (1.15.0 x64) on Linux:

>  [Linter] Error running Terraform Error: spawn terraform ENOENT(…)(anonymous function) @ /home//.atom/packages/linter/lib/linter-registry.js:15

Please let me know if you require more information and I'll provide it.

Regards

**Comment by mschuchard** [comment]
Did you specify the path to your terraform executable or is it in your path when you launch Atom?

**Comment by c2xbrhdj6u4qs15** [comment]
Yep, that did the trick. Thanks for your help
